# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 357ff7b0d1cb1c44b470132ef4fcdde9a0a509a0445ffe9202e11d63bc3acb32bcfed2651b03407986cd0b3edf351560708d84a06be27fd1236dbe2bdafddd63

test:
  secret_key_base: c5d056535998cb8ef0f0f353bac5f394a0973db566f0a03dbd7e9f0304f1fbfdee6f83cd894f4a944cf167d17a4378158e2f91bb76721ecf50c9dae854308682

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
